### ISSUE TITLE
wrong NAV-PVT payoad size?

### ISSUE THREAD

**Issue by thezenox** [bolderflight/UBLOX#1]
I'm working with NEO 6 M Modules but protocol should be the same.
Regarding to protocol documentation:
https://www.u-blox.com/sites/default/files/products/documents/u-blox7-V14_ReceiverDescrProtSpec_%28GPS.G7-SW-12001%29_Public.pdf
the NAV-PVT has a payload of 84 bytes. Checksum is calculated over CLASS, ID, lenght and payload (in total 1+1+2+84 =88 bytes) but UBLOX.h says 
static const uint8_t _payloadSize = 96;
for me it is only working with 88 bytes payloadSize, otherwise checksum fails

**Comment by dollop80** [comment]
The UBX protocol for ublox8 gps receivers has payload size of 96 bytes and it is not backwards compatible with a protocol used by ublox6/7 gps receivers that has payload size of 88 bytes. So you are right, when using the library with receivers older than ublox8 it is needed to change the 
`static const uint8_t _payloadSize = 96 `
to
`static const uint8_t _payloadSize = 88 `
