### ISSUE TITLE
ESP32 empty gps.readSensor()

### ISSUE THREAD

**Issue by max5555** [bolderflight/UBLOX#12]
I have 0 as the output gps.readSensor() despite the fact that at the same time I can see ublox messages in u-center like

`14:45:06  R -> UBX NAV-SAT,  Size 316,  'Satellite Status and Information'`

Here is my code:

`#include <Arduino.h>
#include<HardwareSerial.h>
#define RXD2 16
#define TXD2 17
HardwareSerial gps_serial(2);

#include "UBLOX.h"

UBLOX gps(gps_serial, 9600);

void setup()
{
  // serial to display data
  Serial.begin(921600);

  // starting communication with the GPS receiver
  gps.begin();
  
  Serial.print("Start");
}

void loop()
{
  if (gps.readSensor())
  {
    Serial.print(gps.getNumSatellites()); ///< [ND], Number of satellites used in Nav Solution
    Serial.print("\t");
  }
}`

**Comment by flybrianfly** [comment]
You need UBX-NAV-PVT and UBX-NAV-EOE messages enabled and polled. Optionally, if you have the UBX-NAV-HPPOSLLH available, you should enable and poll that to get higher accuracy data.
