### ISSUE TITLE
Arduino Uno

### ISSUE THREAD

**Issue by boris-gu** [bolderflight/UBLOX#15]
Can I use this library for Arduino Uno?

When compiling my sketch, the error `cstddef: No such file or directory` appears

**Comment by flybrianfly** [comment]
No, from the [installation instructions](https://github.com/bolderflight/ublox#arduino), this library does not support AVR processors.

**Comment by boris-gu** [comment]
What about ESP32?  
I'm sorry if this is a stupid question, I just started working with microcontrollers.

**Comment by flybrianfly** [comment]
Should likely work, I think ESP32 is an ARM processor.
