### ISSUE TITLE
the member named pi does not good idea

### ISSUE THREAD

**Issue by EeeLo** [bolderflight/UBLOX#19]
thanks for the best lib befor, and I'm using this lib to with other project and the error is "pi", I think this is not good idea to using pi in this code.

**Comment by flybrianfly** [comment]
To the best of my knowledge, there is nothing in the library using "pi". Can you please ensure that you're using the latest library downloaded directly from GitHub and provide a screenshot of the error?

**Comment by EeeLo** [comment]
Hi,I'm using "sparkfun sgp4 arduino library" to making a tracking board,this lib using pi,and I think the pi name always in the space calibrtion code,thanks for your good library.

**Comment by flybrianfly** [comment]
Sounds like the issue is not with this library, so I'm closing it.
