### ISSUE TITLE
Configure Receiver from Within Lib

### ISSUE THREAD

**Issue by mjs513** [bolderflight/UBLOX#5]
Hi Brian
A while ago Chris O on the forum updated your Ublox library to read and adjust TP5 parameters for the PPS.  Then I added in a couple of additional commands for setting the NAV5 dynamic model and the Rates (measurement rate and nav rate).  I didn't do a pull request since you seem to have made some changes to the library format.  So I am just attaching the updated zip file:
[UBLOX2.zip](https://github.com/bolderflight/UBLOX/files/2705317/UBLOX2.zip)

**Comment by flybrianfly** [comment]
I'll post on the forum as well, but I think uBlox has a new method to configure receivers and that the approach Chris O used is no longer recommended.

**Comment by flybrianfly** [comment]
Done, configuration is now done within lib.
